---
title: "Automate Candidate Profiles"
output:
  html_document:
    self_contained: false
date: "`r format(Sys.time(), '%d %B, %Y')`"
geometry: paperheight=4.5in,paperwidth=8.5in,margin=1in
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, setup packages, include=FALSE}
library(officer)
library(flextable)
library(magrittr)
library(tidyverse)

set.seed(2023)
```

```{r, fn_setup, include=F}
set.seed(2023)
# select names
# first name data from: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/TYJKEZ
# load data
ln_list <- readxl::read_excel("input/Names_2010Census_Top1000.xlsx", skip = 2)
ln_list

ln_list <- ln_list %>%
  rename_at(
    c(
      "PERCENT NON-HISPANIC OR LATINO WHITE ALONE",
      "PERCENT NON-HISPANIC OR LATINO BLACK OR AFRICAN AMERICAN ALONE"
    ),
    ~ c("percent_white", "percent_black")
  ) %>%
  mutate(across(c("percent_white", "percent_black"), .fns = list(orig = ~.))) %>%
  mutate(across(c("percent_white", "percent_black"), ~ as.numeric(.)))

ln_list %>%
  filter(is.na(percent_white) & !is.na(percent_white_orig))

ln_list %>%
  filter(is.na(percent_black) & !is.na(percent_black_orig))

white_ln <- ln_list %>%
  arrange(desc(percent_white)) %>%
  head(10) %>%
  sample_n(2) %>%
  extract2("SURNAME") %>%
  str_to_sentence() %>%
  str_replace_all("Oconnell", "O'Connell")
white_ln
```

```{r, ln_setup, include=F}
set.seed(1234)
black_ln <- ln_list %>%
  arrange(desc(percent_black)) %>%
  head(10) %>%
  sample_n(2) %>%
  extract2("SURNAME") %>%
  str_to_sentence()
black_ln
```
```{r, include=F}
# names from Bertrand & Mullainathan
set.seed(9999)
white_female <- c("Allison", "Anne", "Carrie", "Emily", "Jill", "Laurie", "Kristen", "Meredith", "Sarah")
black_female <- c("Aisha", "Ebony", "Keisha", "Kenya", "Lakisha", "Latonya", "Latoya", "Tamika", "Tanisha")
white_male <- c("Brad", "Brendan", "Geoffrey", "Greg", "Brett", "Jay", "Matthew", "Neil", "Todd")
black_male <- c("Darnell", "Hakim", "Jamal", "Jermaine", "Kareem", "Leroy", "Rasheed", "Tremayne", "Tyrone")

white_female_fn <- sample(white_female, 2)
black_female_fn <- sample(black_female, 2)

white_male_fn <- sample(white_male, 2)
black_male_fn <- sample(black_male, 2)

black_female_fn
black_male_fn
white_female_fn
white_male_fn
```


```{r, include=F}
categories_to_vary <- c("race_gender", "experience", "career")
levels_per_category <- lst(
  "race_gender" = c(
    "black_female", "black_male",
    "white_female", "white_male"
  ),
  "experience" = c("low", "high"),
  "career" = c("all")
)
levels_grid <- expand.grid(levels_per_category) %>%
  mutate_all(~ as.character(.))
levels_grid
```
```{r, include=F}
set.seed(9999)
first_names <- lst(
  "white_male" = white_male_fn,
  "white_female" = white_female_fn,
  "black_male" = black_male_fn,
  "black_female" = black_female_fn
)

last_names <- lst(
  "black_male" = black_ln,
  "black_female" = black_ln,
  "white_male" = white_ln,
  "white_female" = white_ln
)

experience <- lst(
  "high" = sample(c("State legislator", "Member of Congress"), 2),
  "low" = c("No experience", "No experience")
)
career <- lst("all" = sample(c("Restaurant owner", "Small business owner"), 2))

ages <- c(39, 72)

first_names
last_names
```

```{r, include=F}
# random_order <- function(x) {
#   return(sample(x, length(x), replace = F))
# }
#
# generate_data <- function(orig_df) {
#   return(map(orig_df, ~random_order(.)))
# }
#
# rand_data <- generate_data(orig_df)
# rand_data
```

\newpage

```{r, results='asis'}
for (c in 1:nrow(levels_grid)) {
  cat("<br>")
  cat(str_c(
    "Race and gender: ", levels_grid[c, ][["race_gender"]],
    ", Political experience: ", levels_grid[c, "experience"]
  ) %>%
    str_replace("_", " "))

  fn <- first_names[[levels_grid[c, ][["race_gender"]]]]
  ln <- last_names[[levels_grid[c, ][["race_gender"]]]]
  exp <- experience[[levels_grid[c, "experience"]]]
  car <- career[[levels_grid[c, "career"]]]

  orig_df <- lst(
    "first_names" = fn,
    "last_names" = ln,
    "ages" = ages,
    "experience" = exp,
    "career" = car
  )

  for (i in 1:length(ages)) {
    j <- if_else(i == 1, 2, 1)

    #      table_text_latex <- str_c("\\begin{framed}
    #     \\noindent Imagine you are a voter in a primary election for state governor.\\\\The party you prefer puts forth two candidates: \\vskip .2in \\begin{tabular}{lll}
    #         & Candidate 1 & Candidate 2 \\\\
    #         \\hline
    #         Name & ", orig_df$first_names[1], " ", orig_df$last_names[1],
    #     " & ", orig_df$first_names[2], " ", orig_df$last_names[2], " \\\\ Age &",
    #     orig_df$ages[i], " & ", orig_df$ages[j], "\\\\
    #         Political experience & ", orig_df$experience[1], " & ", orig_df$experience[2], " \\\\
    #         Career experience & ", orig_df$career[1], " & ", orig_df$career[2], " \\\\
    #         \\hline \\end{tabular} \\vskip .2in
    # \\end{framed} \\vskip .5in \\clearpage")

    table_text <- str_c(
      "
        <table>
        <tr><th></th><th>Candidate 1</th> <th>Candidate 2</th></tr>
        <tr><td>Name</td><td>", orig_df$first_names[1], " ", orig_df$last_names[1],
      "</td><td>", orig_df$first_names[2], " ", orig_df$last_names[2], "</td></tr><tr><td>Ages</td><td>",
      orig_df$ages[i], "</td><td>", orig_df$ages[j], "</td></tr><tr><td>Political experience</td><td>", orig_df$experience[1], "</td><td>", orig_df$experience[2], "</td></tr><tr><td>Career experience</td><td>", orig_df$career[1], "</td><td>", orig_df$career[2], "</td></tr></table><br><par>Which of these two candidates do you prefer?</par>"
    )
    cat("<br>")
    cat(table_text)
  }
}
```

