---
title: "Automate Resume Creation"
output: html_document
date: "2023-09-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, setup}
library(officer)
library(flextable)
library(magrittr)
library(tidyverse)

set.seed(2023)
```

```{r}
race <- c("W", "B")
white_first_name <- c("Jessica", "Ashley")
white_last_name <- c("Olsen", "Snyder")
black_first_name <- c("Ebony", "Aisha")
black_last_name <- c("Washington", "Jefferson")

university_rank <- c("Low", "High")
university_lowrank <- c("University of Denver", "University of Arizona")
university_highrank <- c("Massachusetts Institute of Technology", "University of Pennsylvania")

treatment <- c(
  "Parent Teacher Association Volunteer",
  "Marketing Coordinator"
)
treatment_header <- c(
  "| Creekside Elementary | Denver, CO 80014 | 2022 <U+2013> present",
  "| Goods Delivered | Denver, CO | 2021 to Present"
)
treatment_description <- c(
  "Member of the Executive Board. Served as Secretary.",
  "Report directly to Marketing Manager, assisting in the development of the overall marketing strategy."
)
treatment_year <- c("(left to care for my children)", "")
```

```{r}
copies <- 10
for (i in c(1:copies)) {
  r <- sample(race, 1)[[1]]
  name_order <- sample(c(1, 2), replace = F)
  fn <- if (r == "W") {
    white_first_name[name_order]
  } else {
    black_first_name[name_order]
  }
  ln <- if (r == "W") {
    white_last_name[name_order]
  } else {
    black_last_name[name_order]
  }

  univ_order <- sample(c(1, 2), replace = F)
  univ_rank <- sample(university_rank, 1)
  univ <- if (univ_rank == "High") {
    university_highrank[univ_order]
  } else {
    university_lowrank[univ_order]
  }

  format <- sample(c(1, 2), replace = F)
  treatment_order <- sample(c(1, 2), replace = F)
  t <- treatment[treatment_order]
  t_head <- treatment_header[treatment_order]
  t_desc <- treatment_description[treatment_order]
  t_year <- treatment_year[treatment_order]

  for (j in c(1:2)) {
    doc <- read_docx(str_glue("resume_format{format[j]}.docx")) %>%
      body_replace_all_text(
        old_value = "FirstName",
        new_value = fn[j], fixed = TRUE
      ) %>%
      body_replace_all_text(
        old_value = "firstname",
        new_value = str_to_lower(fn[j]), fixed = TRUE
      ) %>%
      body_replace_all_text(
        old_value = "LastName",
        new_value = ln[j], fixed = TRUE
      ) %>%
      body_replace_all_text(
        old_value = "lastname",
        new_value = str_to_lower(ln[j]), fixed = TRUE
      ) %>%
      body_replace_all_text(
        old_value = "University",
        new_value = univ[j], fixed = TRUE
      ) %>%
      body_replace_all_text(
        old_value = "TreatmentDescription",
        new_value = t_desc[j], fixed = TRUE
      ) %>%
      body_replace_all_text(
        old_value = "TreatmentHeader",
        new_value = t_head[j], fixed = TRUE
      ) %>%
      body_replace_all_text(
        old_value = "Treatment",
        new_value = t[j], fixed = TRUE
      ) %>%
      body_replace_all_text(
        old_value = "YEAR",
        new_value = t_year[j], fixed = TRUE
      )

    doc %>%
      print(target = str_glue("output/resume_output{i}_{format[j]}_race{r}_universityrank{univ_rank}.docx"))
  }
}
```

```



