---
title: "Automate Resume Creation"
output: html_document
date: "2023-09-14"
---

```{r setup, include=F}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, setup_packages, include=F}
library(officer)
library(flextable)
library(magrittr)
library(tidyverse)

set.seed(2023)
```

```{r, include=F}
copies <- 2
categories_to_vary <- c("university", "race")
levels_per_category <- lst(
  "university" = c("low", "high"),
  "race" = c("black", "white")
)
levels_grid <- expand.grid(levels_per_category) %>%
  mutate(across(everything(), ~ as.character(.)))
levels_grid
```

```{r, include=F}
set.seed(9999)
first_names <- lst(
  "white" = c("Jessica", "Ashley"),
  "black" = c("Tanisha", "Keisha")
)

last_names <- lst(
  "white" = c("Schmitt", "O'Connell"),
  "black" = c("Rivers", "Mosely")
)
```

```{r, include=F}
# randomly select universities
set.seed(9999)
pool_high <- c("Massachusetts Institute of Technology", "University of Pennsylvania")
pool_low <- c("California State University, Long Beach", "San Diego State University")


university <- lst(
  "high" = sample(pool_high, 2),
  "low" = sample(pool_low, 2)
)

university
```

```{r, include=F}
treatment <- c(
  "Parent Teacher Association Volunteer",
  "Volunteer Treasurer"
)
treatment_header <- c(
  "| Creekside Elementary | 2022 <U+2013> present",
  "| Riverview Neighborhood Association | 2022 - present"
)

treatment_description <- c(
  "Member of the Executive Board. Served as Secretary.",
  ""
)
```

```{r, include=F}
# random_order <- function(x) {
#   return(sample(x, length(x), replace = F))
# }
#
# generate_data <- function(orig_df) {
#   return(map(orig_df, ~ random_order(.)))
# }
```

```{r, include=F}
phone_numbers <- c("(303) 555-0146", "720-555-0182")
majors <- c("B.S. in Business Administration; Marketing", "B.A. in Marketing, Digital Marketing Minor")
position1 <- c(
  '<span style="color:black">Marketing Coordinator </span></span></span></b><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif"><span style="color:black">| Goods Delivered | 2021 to Present',
  '<span style="color:black">Marketing Coordinator </span></span></span></b><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif"><span style="color:black">| Local Guiding | 2021 &ndash; present'
)
position_desc1 <- c(
  "Report directly to Marketing Manager, assisting in the development of the overall marketing strategy.",
  "Crafted SEO-friendly website, blog, and social media content, telling the organization<U+2019>s story across platforms."
)

position2 <- c(
  'Marketing Coordinator </span></span></span></b><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif"><span style="color:black">| Live Healthy | 2017 to 2021',
  'Digital Marketing Coordinator </span></span></span></b><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif"><span style="color:black">| Cloud Sales Support | 2017 &ndash; 2021'
)
position_desc2 <- c(
  "Supported a team of four marketing account executives responsible for 12 client accounts in the healthcare industry.",
  "Coordinate digital marketing operations for 20+ monthly inbound and outbound campaigns across email, web, and social media for an emerging fintech startup."
)
```

```{r, results='asis', echo=F}
for (c in 1:nrow(levels_grid)) {
  cat("<br>")
  cat(str_c(
    "Race: ", levels_grid[c, ][["race"]],
    ", Education: ", levels_grid[c, ][["university"]]
  ) %>%
    str_replace("_", " "))

  fn <- first_names[[levels_grid[c, "race"]]]
  ln <- last_names[[levels_grid[c, "race"]]]
  univ <- university[[levels_grid[c, "university"]]]

  orig_df <- lst(
    "first_names" = fn,
    "last_names" = ln,
    "university" = univ
  )


  for (ord in 1:2) {
    if (ord == 1) {
      treatment_order <- c(1, 2)
    } else {
      treatment_order <- c(2, 1)
    }
    t <- treatment[treatment_order]

    t_head <- treatment_header[treatment_order]
    t_desc <- treatment_description[treatment_order]
    for (j in 1:2) {
      resume_text <- str_c(
        '<div class="resume"><span style="font-size:12pt"><span style="font-family:Cambria,serif"><b><span style="font-size:16.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif"><span style="color:black">',
        orig_df$first_names[j], " ", orig_df$last_names[j], '&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span></b></span></span><br />
    <span style="font-size:12pt"><span style="font-family:Cambria,serif"><b><span style="font-size:14.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif"><span style="color:black">Marketing Coordinator</span></span></span></b></span></span>
    <div style="border-bottom:solid black 1.0pt; padding:0in 0in 0in 0in"><span style="font-size:12pt"><span style="font-family:Cambria,serif"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif"><span style="color:black">', phone_numbers[j], " | ",
        str_to_lower(orig_df$first_names[[j]]), ".",
        str_to_lower(orig_df$last_names[j]), "@gmail.com | LinkedIn.com/",
        orig_df$first_names[j], ".", orig_df$last_names[[j]],
        '</span></span></span></span></span><br />
    <span style="font-size:12pt"><span style="font-family:Cambria,serif"><b><span style="font-family:&quot;Calibri&quot;,sans-serif"><span style="color:black">Education&nbsp;</span></span></b></span></span></div><span style="font-size:12pt"><span style="font-family:Cambria,serif"><b><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif"><span style="color:black">',
        majors[j], ' </span></span></span></b><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif"><span style="color:black">| ',
        orig_df$university[j],
        ' | 2010</span></span></span></span></span><br />&nbsp;<div style="border-bottom:solid black 1.0pt; padding:0in 0in 1.0pt 0in"><span style="font-size:12pt"><span style="font-family:Cambria,serif"><b><span style="font-family:&quot;Calibri&quot;,sans-serif"><span style="color:black">Professional Experience</span></span></b></span></span></div><span style="font-size:12pt"><span style="font-family:Cambria,serif"><b><span style="font-size:10.5pt"><span style="font-family:&quot;Calibri&quot;,sans-serif"><span style="color:black">',
        position1[j],
        '</span></span></span></span></span><ul><li><span style="font-size:12pt"><span style="color:black"><span style="tab-stops:list .5in"><span style="vertical-align:baseline"><span style="font-family:Cambria,serif"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">',
        position_desc1[j],
        '</span></span></span></span></span></span></span></li></ul><span style="font-size:12pt"><span style="font-family:Cambria,serif"><b><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif"><span style="color:black">',
        position2[j],
        '</span></span></span></span></span><ul><li><span style="font-size:12pt"><span style="color:black"><span style="tab-stops:list .5in"><span style="vertical-align:baseline"><span style="font-family:Cambria,serif"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">',
        position_desc2[j],
        '</span></span></span></span></span></span></span></li></ul><div style="page-break-after:always"><span style="display: none;">&nbsp;</span></div><div style="border-bottom:solid black 1.0pt; padding:0in 0in 1.0pt 0in"><span style="font-size:12pt"><span style="font-family:Cambria,serif"><b><span style="font-family:&quot;Calibri&quot;,sans-serif"><span style="color:black">Volunteer Experience</span></span></b></span></span></div><li><span style="font-size:12pt"><span style="color:black"><span style="tab-stops:list .5in"><span style="vertical-align:baseline"><span style="font-family:Cambria,serif"><span style="font-size:11.0pt"><span style="font-family:&quot;Calibri&quot;,sans-serif">',
        t[j], t_head[j], '</span></span></span></span></span></span></span></li></ul><div style="page-break-after:always"><span style="display: none;">&nbsp;</span></div><br>&nbsp;</div>'
      )

      cat("<br>")
      cat(resume_text)
    }
  }
}
```




